const {app} = require("electron");

function getDefaultSettings() {
    return {
        autoUpdate: true,
        theme: 'auto',
        downloadLocation: app.getPath('downloads'),
        createPlatformSubfolders: false,
        orpheusDL: false,
        use_cookies: false,
        cookies: "",
        cookies_from_browser: "",
        override_download_extension: false,
        yt_override_download_extension: false,
        ytm_override_download_extension: false,
        youtubeVideoExtensions: "mp4",
        youtubeAudioExtensions: "mp3",
        use_aria2: false,
        auto_update: true,
        max_downloads: 0,
        download_speed_limit: false,
        speed_limit_type: 'M',
        speed_limit_value: 0,
        max_retries: 5,
        download_output_template: "%(title)s.%(ext)s",
        continue: true,
        add_metadata: false,
        embed_chapters: false,
        add_subtitle_to_file: false,
        use_proxy: false,
        proxy_url: "",
        use_authentication: false,
        username: "",
        password: "",
        sponsorblock_mark: "all",
        sponsorblock_remove: "",
        sponsorblock_chapter_title: "[SponsorBlock]: %(category_names)l",
        no_sponsorblock: false,
        sponsorblock_api_url: "https://sponsor.ajay.app",

        disc_subdirectories: true,
        concurrency: true,
        max_connections: 6,
        requests_per_minute: 60,
        qobuz_download_booklets: true,
        qobuz_token_or_email: false,
        qobuz_email_or_userid: "",
        qobuz_password_or_token: "",
        qobuz_app_id: "",
        qobuz_secrets: "",
        tidal_download_videos: false,
        tidal_user_id: '',
        tidal_country_code:"",
        tidal_access_token:"",
        tidal_refresh_token: "",
        tidal_token_expiry: "",
        deezer_use_deezloader: false,
        deezer_arl: "",
        deezloader_warnings: true,

        downloads_database_check: false,
        downloads_database: "",
        failed_downloads_database_check: false,
        failed_downloads_database: "",
        conversion_check: false,
        conversion_codec: "FLAC",
        conversion_sampling_rate: null,
        conversion_bit_depth: null,
        conversion_lossy_bitrate: 320,
        meta_album_name_playlist_check: false,
        meta_album_order_playlist_check: false,
        meta_exclude_tags_check: false,
        excluded_tags: "",
        filepaths_add_singles_to_folder: true,
        filepaths_folder_format: "{albumartist} - {album} ({year})",
        filepaths_track_format: "{tracknumber:02}. {artist} - {title}{explicit}",
        filepaths_restrict_characters: true,
        filepaths_truncate_to: 120,
        embed_cover: true,
        save_cover: false,
        save_lrc_files: false,
        qobuz_filters_extras: false,
        qobuz_repeats: false,
        qobuz_non_albums: false,
        qobuz_features: false,
        qobuz_non_studio_albums: false,
        qobuz_non_remaster: false,
        soundcloud_quality: 0,
        soundcloud_client_id: "",
        soundcloud_app_version: "",
        youtube_quality: 0,
        youtube_download_videos: false,
        youtube_video_downloads_folder: "",
        lastfm_source: "qobuz",
        lastfm_fallback_source: "",
        cli_text_output: true,
        cli_progress_bars: true,
        cli_max_search_results: "100",
        spotify_client_id: "",
        spotify_client_secret: "",
        tidal_client_id: "",
        tidal_client_secret: "",
        youtube_api_key: "",

        spotify_cookies_path: "",
        spotify_output_path: "",
        spotify_audio_download_mode: "ytdlp",
        spotify_audio_remux_mode: "ffmpeg",
        spotify_video_format: "mp4",
        spotify_video_resolution: "1080p",
        spotify_video_remux_mode: "ffmpeg",
        spotify_cover_size: "large",
        spotify_wvd_path: "",
        spotify_no_drm: false,
        spotify_wait_interval: 10,
        spotify_overwrite: false,
        spotify_no_synced_lyrics_file: false,
        spotify_save_playlist_file: false,
        spotify_save_cover_file: false,
        spotify_synced_lyrics_only: false,
        spotify_album_folder_template: "{album_artist}/{album}",
        spotify_compilation_folder_template: "Compilations/{album}",
        spotify_podcast_folder_template: "{podcast_name}",
        spotify_no_album_folder_template: "{album_artist}/Unknown Album",
        spotify_single_disc_file_template: "{track:02d} {title}",
        spotify_multi_disc_file_template: "{disc}-{track:02d} {title}",
        spotify_podcast_file_template: "{episode_number} - {title}",
        spotify_no_album_file_template: "{title}",
        spotify_playlist_file_template: "Playlists/{playlist_title}/{track:02d} {title}",
        spotify_date_tag_template: "%Y-%m-%dT%H:%M:%SZ",
        spotify_truncate: 40,
        spotify_exclude_tags: "",
        spotify_log_level: "INFO",
        spotify_no_exceptions: false,
        spotify_artist_media_option: "albums",
        spotify_prefer_video: false,

        apple_cookies_path: "",
        apple_output_path: "Apple Music",
        apple_temp_path: "temp",
        apple_download_mode: "ytdlp",
        apple_remux_mode: "ffmpeg",
        apple_cover_format: "jpg",
        apple_cover_size: 1200,
        apple_save_cover: true,
        apple_synced_lyrics_format: "lrc",
        apple_synced_lyrics_only: false,
        apple_no_synced_lyrics: false,
        apple_template_folder_album: "{album_artist}/{album}",
        apple_template_folder_compilation: "Compilations/{album}",
        apple_template_file_single_disc: "{track:02d} {title}",
        apple_template_file_multi_disc: "{disc}-{track:02d} {title}",
        apple_template_folder_no_album: "{album_artist}/Unknown Album",
        apple_template_file_no_album: "{title}",
        apple_template_file_playlist: "Playlists/{playlist_title}/{track:02d} {title}",
        apple_date_tag_template: "%Y-%m-%dT%H:%M:%SZ",
        apple_save_playlist: true,
        apple_overwrite: true,
        apple_language: "en-US",
        apple_truncate: 40,
        apple_exclude_tags: "",
        apple_log_level: "INFO",
        apple_use_album_date: false,
        apple_fetch_extra_tags: false,
        apple_no_exceptions: false,
        apple_mv_enabled: false,
        apple_mv_codec_priority: "h264",
        apple_mv_remux_format: "m4v",
        apple_mv_resolution: "1080p",
        apple_uploaded_video_quality: "best",
        apple_custom_paths_enabled: false,
        apple_nm3u8dlre_path: "N_m3u8DL-RE",
        apple_mp4decrypt_path: "mp4decrypt",
        apple_ffmpeg_path: "ffmpeg",
        apple_mp4box_path: "MP4Box",
        apple_wvd_path: "",
        apple_use_wrapper: false,
        apple_wrapper_account_url: "",
        apple_wrapper_decrypt_ip: "",
    };
}

module.exports = { getDefaultSettings };