const path = require("path");
const {app} = require("electron");

function getDefaultSettings() {
    return {
        autoUpdate: true,
        firstTime: true,
        theme: 'auto',
        downloadsDatabasePath: path.join(app.getPath('home'), 'MH', 'database.db'),
        downloadLocation: app.getPath('downloads'),
        createPlatformSubfolders: false,
        orpheusDL: false,
        streamrip: true,
        use_cookies: false,
        cookies: "",
        cookies_from_browser: "",
        override_download_extension: false,
        yt_override_download_extension: false,
        ytm_override_download_extension: false,
        youtubeVideoExtensions: "mp4",
        youtubeAudioExtensions: "mp3",
        use_aria2: false,
        auto_update: true,
        max_downloads: 0,
        download_speed_limit: false,
        speed_limit_type: 'M',
        speed_limit_value: 0,
        max_retries: 5,
        download_output_template: "%(title)s.%(ext)s",
        continue: true,
        add_metadata: false,
        embed_chapters: false,
        add_subtitle_to_file: false,
        use_proxy: false,
        proxy_url: "",
        use_authentication: false,
        username: "",
        password: "",
        sponsorblock_mark: "all",
        sponsorblock_remove: "",
        sponsorblock_chapter_title: "[SponsorBlock]: %(category_names)l",
        no_sponsorblock: false,
        sponsorblock_api_url: "https://sponsor.ajay.app",

        // Streamrip settings
        disc_subdirectories: true,
        concurrency: true,
        max_connections: 6,
        requests_per_minute: 60,
        // Qobuz
        qobuz_quality: 3,
        qobuz_download_booklets: true,
        qobuz_token_or_email: false,
        qobuz_email_or_userid: "",
        qobuz_password_or_token: "",
        qobuz_app_id: "",
        qobuz_secrets: "",
        // Tidal
        tidal_download_videos: false,
        tidal_quality: '3',
        tidal_user_id: '',
        tidal_country_code:"",
        tidal_access_token:"",
        tidal_refresh_token: "",
        tidal_token_expiry: "",
        // Deezer
        deezer_quality: 1,
        deezer_use_deezloader: false,
        deezer_arl: "",
        deezloader_warnings: true,

        downloads_database_check: false,
        downloads_database: "",
        failed_downloads_database_check: false,
        failed_downloads_database: "",
        conversion_check: false,
        conversion_codec: "MP3",
        conversion_sampling_rate: 44100,
        conversion_bit_depth: 16,
        conversion_lossy_bitrate: 320,
        meta_album_name_playlist_check: false,
        meta_album_order_playlist_check: false,
        meta_exclude_tags_check: false,
        excluded_tags: "",
        filepaths_add_singles_to_folder: true,
        filepaths_folder_format: "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]",
        filepaths_track_format: "{tracknumber:02}. {artist} - {title}{explicit}",
        filepaths_restrict_characters: true,
        filepaths_truncate_to: 120,
        // These will be added  to GUI after adding discography artist on search
        qobuz_filters_extras: false,
        qobuz_repeats: false,
        qobuz_non_albums: false,
        qobuz_features: false,
        qobuz_non_studio_albums: false,
        qobuz_non_remaster: false,
        // these to fix streamrip config issue
        soundcloud_quality: 0,
        soundcloud_client_id: "",
        soundcloud_app_version: "",
        youtube_quality: 0,
        youtube_download_videos: false,
        youtube_video_downloads_folder: "",
        lastfm_source: "qobuz",
        lastfm_fallback_source: "",
        cli_text_output: true,
        cli_progress_bars: true,
        cli_max_search_results: "100",
        // Spotify (Zotify) Settings
        zotify_userName: "",
        spotify_audio_format: "mp3",
        spotify_transcode_bitrate: -1,
        spotify_ffmpeg_args: "",
        spotify_download_quality: "auto",
        spotify_artwork_size: "large",
        spotify_save_subtitles: false,
        spotify_lyrics_file: false,
        spotify_lyrics_only: false,
        spotify_create_playlist_file: true,
        spotify_save_metadata: true,
        spotify_replace_existing: false,
        spotify_skip_previous: true,
        spotify_skip_duplicates: true,
        spotify_output_album: "{album_artist}/{album}/{track_number}. {artists} - {title}",
        spotify_output_playlist_track: "{playlist}/{artists} - {title}",
        spotify_output_playlist_episode: "{playlist}/{episode_number} - {title}",
        spotify_output_podcast: "{podcast}/{episode_number} - {title}",

        // Apple Settings
        apple_cookies_path: "",
        apple_output_path: "Apple Music",
        apple_temp_path: "temp",
        apple_download_mode: "ytdlp",
        apple_remux_mode: "ffmpeg",
        apple_cover_format: "jpg",
        apple_synced_lyrics_format: "lrc",
        apple_template_folder_album: "{album_artist}/{album}",
        apple_template_folder_compilation: "Compilations/{album}",
        apple_template_file_single_disc: "{track:02d} {title}",
        apple_template_file_multi_disc: "{disc}-{track:02d} {title}",
        apple_disable_music_video_skip: true,
        apple_save_cover: true,
        apple_overwrite: true,
        apple_save_playlist: true,
        apple_synced_lyrics_only: true,
        apple_no_synced_lyrics: false,
        apple_cover_size: 1200,
    };
}

module.exports = { getDefaultSettings };